name: Build and Push Docker Images on Tag

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - name: linux-gcc
            context: ./qt/linux/gcc-aqt/
          - name: macos
            context: ./qt/macos/
          - name: flatpak
            context: ./flatpak-builder/

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: "0verengineer"
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract tag name
        id: vars
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Build Docker image with tag
        run: |
          docker build -t 0verengineer/aqt-conan-ci-containers-${{ matrix.name }}:${{ steps.vars.outputs.TAG }} ${{ matrix.context }}

      - name: Push Docker image
        run: |
          docker push 0verengineer/aqt-conan-ci-containers-${{ matrix.name }}:${{ steps.vars.outputs.TAG }}
